#!/bin/bash
gcc -std=gnu99 -o enc_server enc_server.c
gcc -std=gnu99 -o enc_client enc_client.c
gcc -std=gnu99 -o dec_server dec_server.c
gcc -std=gnu99 -o dec_client dec_client.c
gcc -std=gnu99 -o keygen keygen.c
# had to include -std=gnu99 to compile in OS1 server
